type Query {
  items: [Item!]!
  item(id: ID!): Item!
}

type Mutation {
  createItem(input: CreateItemInput!): Item!
  updateItem(id: ID!, input: UpdateItemInput!): Item!
  removeItem(id: ID!): Item!
}

type Item {
  id: ID!
  type: String!
  is_deleted: Boolean
}

input CreateItemInput {
  type: String!
  is_deleted: Boolean
}

input UpdateItemInput {
  type: String
  is_deleted: Boolean
}
